### ISSUE TITLE
move readme to root

### ISSUE THREAD

**Issue by bj-jiwrajka** [Dimpal-Kalita/RandomWorks#1]
Hi, 

The readme file should be the in the root folder instead of the subdirectory. This will make things convenient for us.

Thank You. 

_(you can also give the write access to ```bj-jiwrajka``` if you feel it to tedious to do)_

**Comment by Dimpal-Kalita** [comment]
[Crawl-Nutch-Tomcat](https://github.com/Dimpal-Kalita/RandomWorks/tree/main/Crawl-Nutch-Tomcat)  is only a directory, I am thinking of including more useless things in this GitHub repo, all of them will have different `README` depending on the project. So, I have no intention to move it to the `root` folder
